# -*- coding: utf-8 -*-
"""retorno diario e acumulado

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-UGJfJojKCh_SinOYpAiaKiNo8H1GnWA
"""

import pandas as pd
import numpy as np
import yfinance as yf
import seaborn as sns

"""#configurando carteira!

"""

ativos = [
"BPAC11.SA"
,"ITUB3.SA"
,"VALE3.SA"
,"EGIE3.SA"
,"WEGE3.SA"
,"IVVB11.SA"

]


#importando os dados
inicio = "2018-01-01"
fim = "2023-12-31"

carteira = yf.download(ativos,start=inicio,end = fim)["Adj Close"]
display(carteira)

pesos = np.array([0.1,0.1,0.1,0.1,0.1,0.1])

(carteira/carteira.iloc[0]).plot()

"""# retorno diario e acumulado

"""

#retorno diario -> variacao no dia
#retorno acumulado -> retorno total ao longo do tempo

retornos = carteira.pct_change()

#retorno diario da carteira
retorno_carteira = (retornos*pesos).sum(axis = 1)
retorno_carteira.plot()

"""# Retorno acumulado"""

retorno_acumulado_carteira = (1 + retorno_carteira).cumprod() - 1
retorno_acumulado_carteira.plot()

"""# Comparativo de desempenho"""

ibov = yf.download("^BVSP", start=inicio,end= fim) ["Adj Close"]
ibov_retorno_diario = ibov.pct_change()
retorno_acumulado_ibov = (1 + ibov_retorno_diario ).cumprod() - 1

retorno_portfolio = pd.DataFrame()
retorno_portfolio["Retorno Carteira"] = retorno_acumulado_carteira

retorno_portfolio["Retorno IBOV"] = retorno_acumulado_ibov
retorno_portfolio = retorno_portfolio.dropna()

retorno_portfolio.plot()