# -*- coding: utf-8 -*-
"""carteira_inv_hashtag

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LR6HLQChC2NCdGab7gZGoBwpN5A95oL
"""

!pip install alpha_vantage

import pandas as pd
import numpy as np
from alpha_vantage.timeseries import TimeSeries

carteira = pd.read_excel("Carteira.xlsx")
data_inicial = "2023-01-09"
display(carteira)

acoes = []
for acao in carteira["Ativos"]:
  acoes.append(acao + "SA")

acoes

import yfinance as yf


precos = yf.download(acoes , start = data_inicial, progress = False)['Adj Close']

precos

ibov = yf.download('^BVSP', start = data_inicial)['Adj Close']

display(ibov)
ibov.plot()

precos["BPAC11.SA"]

tabela_cotacoes = pd.DataFrame()

for acao in precos:
  tabela_cotacoes[acao] = precos[acao].loc[data_inicial:]

display(tabela_cotacoes)

valor_investir = 10000
quantidade_acoes = []

for acao in carteira["Ativos"]:
    preco_inicial = tabela_cotacoes[acao + ".SA"].iloc[0]
    qtde = valor_investir // preco_inicial
    quantidade_acoes.append(qtde)

carteira["Qtde"] = quantidade_acoes
display(carteira)

tabela_cotacoes["Total"] = tabela_cotacoes.sum(axis = 1)


display(tabela_cotacoes)

carteira_ajustado = tabela_cotacoes["Total"]/ tabela_cotacoes["Total"].iloc[0]
ibov_ajustado = ibov/ibov.iloc[0]

import matplotlib.pyplot as plt

carteira_ajustado.plot(label="Carteira")
ibov_ajustado.plot(label="IBOV")
plt.legend()
plt.show()

retorno_carteira = carteira_ajustado[-1] - 1

retorno_ibov = ibov_ajustado[-1] - 1

print(f"""Retorno Carteira = {retorno_carteira} % \n
Retorno IBOV = {retorno_ibov} %""")