# -*- coding: utf-8 -*-
"""CO2 Emission by countries Year wise (1750-2022)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-dyhmnQoYoz8SpJqWf6xOk4iHUs6so_Y
"""

import pandas as pd
import numpy as np

"""[Dados de emissao de CO2 por país para a análise](https://www.kaggle.com/datasets/moazzimalibhatti/co2-emission-by-countries-year-wise-17502022/data)"""

df = pd.read_csv("CO2 emission by countries.csv",sep=",",encoding='unicode_escape')
display(df)

# Pega amostra de todas as colunas
df_sample = df.head(20)
df_sample.to_csv('sampleH.csv')
df_sample

df.info()

df = df.drop(["Calling Code","Code",'% of World',"Area"], axis=1)

display(df)

df.info()

df.head()

df = df.groupby('Country').sum()

df = df.drop(["Year","Population(2022)"], axis=1)

df['CO2 emission (Tons)'] = df['CO2 emission (Tons)'].map('{:.0f}'.format)
df

display(df)

df.loc["United States"]

df_2= df.copy()

# Converte coluna para float
df_2["CO2 emission (Tons)"] = df_2["CO2 emission (Tons)"].astype(float)

# Agora aplica a formatação
df_2["CO2 col_formatada"] = df_2["CO2 emission (Tons)"].apply(lambda x: '{:,.2f}'.format(x).replace(',', '.'))

"""# **Emissão média de cada pais ao longo de 272 anos **
### Diferença de tempo entre inicio da revolução industrial, 1750, até o ano dos dados 2022
"""

df_2["Media de emissão anual de CO2"] = df_2["CO2 emission (Tons)"]/272

display(df_2)
#df_2.info()

df_2["Media formatada"] = df_2["Media de emissão anual de CO2"].apply(lambda x: '{:,.2f}'.format(x))#.replace(',', '.'))
display(df_2)

"""#Ranking de emissão média anul de CO2 por pais"""

df_ordenado = df_2.copy()

df_ordenado = df_ordenado.sort_values(by='Media de emissão anual de CO2', ascending=False)

display(df_ordenado)