# -*- coding: utf-8 -*-
"""simulaçao de carteira

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ChDkE52XnQit1ELfFxNnVoTsn17inrg
"""

import pandas as pd
import yfinance as yf
import numpy as np

"""Aporte em uma ação, realizados todos no mesmo dia"""

#configurando carteira!
compras = {
"BPAC11.SA" : 1500
,"ITUB3.SA" : 1500
,"VALE3.SA" : 500
,"EGIE3.SA" : 1500
,"WEGE3.SA" : 1000
,"IVVB11.SA" : 1000

           }
compras.keys()

#importando os dados
inicio = "2018-01-01"
fim = "2023-12-31"

precos = yf.download(list(compras.keys()),start=inicio,end = fim)["Adj Close"]
display(precos)

"""# Simulacao da carteira ficticia"""

primeiro =  precos.iloc[0]

compras_df = pd.Series(data = compras, index = list(compras.keys()))
compras_df

qnt_acoes = round(compras_df/primeiro , 0)
qnt_acoes

pl = precos*qnt_acoes
pl

pl["PL Total"] =pl.sum(axis = 1) #eixo 0 -> eixo linhas ----- eixo 1-> eixo colunas

pl.head()

pl.tail()

"""# Comparando com  o IBOV"""

ibov = yf.download("^BVSP", start=inicio,end= fim) ["Adj Close"]

ibov = pd.DataFrame(ibov)
ibov.rename(columns = {"Adj Close" : "IBOV"},inplace = True)
display(ibov)

consolidado = pd.merge(ibov,pl, how ="inner", on = "Date")

consolidado.head()

"""# Normalizando os dados e ajustando em escala

"""

import seaborn as sns
import matplotlib.pyplot as plt

consolidado_ajustado = consolidado/consolidado.iloc[0]

consolidado_ajustado[["IBOV", "PL Total"]].plot()

sns.lineplot(data=consolidado_ajustado[["IBOV", "PL Total"]])

"""# Funcao para simular carteira

"""

def simulacao_carteira(inicio, fim, carteira):
  precos = yf.download(list(carteira.keys()), start = inicio, end = fim, progress = False)['Adj Close']
  primeiro = precos.iloc[0]
  compras_df = pd.Series(data = carteira, index = list(carteira.keys()))
  qtd_acoes = compras_df/primeiro
  qtd_acoes = round(qtd_acoes,0)
  PL = precos*qtd_acoes
  PL['PL Total'] = PL.sum(axis = 1)
  ibov = yf.download('^BVSP', start = inicio, end =  fim, progress = False)
  ibov.rename(columns = {'Adj Close': 'IBOV'}, inplace = True)
  ibov.drop(ibov.columns[[0,1,2,3,5]], axis = 1, inplace = True)
  consolidado = pd.merge(ibov, PL, how = 'inner', on = 'Date')
  consolidado_adj = consolidado/consolidado.iloc[0]
  consolidado_adj[['IBOV', 'PL Total']].plot(figsize = (8,6));

fiis = {
"HGLG11.SA" : 1500
,"BTLG11.SA" : 1500
,"XPML11.SA" : 500
,"MXRF11.SA" : 1500
,"KNRI11.SA" : 1000
,"XPLG11.SA" : 1000

           }

simulacao_carteira(inicio,fim,fiis)